apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- iot-consumer/manifests
- iot-frontend/manifests
- iot-software-sensor/manifests
- iot-software-sensor-quarkus/manifests

# Open data hub is optional
# - iot-anomaly-detection/manifests


